### ISSUE TITLE
Issue in Readme

### ISSUE THREAD

**Issue by plm75** [antoninbiret/RxEureka#1]
Hi, just to let you know that in the readme file you should maybe change the installation section with the following:

pod 'RxEureka', :git => 'https://github.com/antoninbiret/RxEureka'

instead of 
pod "RxEureka", :git => 'git@github.com/antoninbiret/RxEureka', :branch => 'master' (which doesn't seem to work, for me at least)

Cheers

**Comment by antoninbiret** [comment]
Well spotted @plm75. I'm going to update the readme asap. 👍
