### ISSUE TITLE
EXC_BAD_ACCESS when trying to print object

### ISSUE THREAD

**Issue by sedwo** [antoninbiret/RxEureka#16]
Forgive my newly found ignorance with RxSwift, but after binding:
```
private func configureBindings() {

    // Bind 'email' row to variable
    self.emailRow!.rx.value
        .asObservable()
        .bind(to: self.viewModel.usernameText)
        .disposed(by: self.disposeBag)

    // Bind variable to 'email' row
    self.viewModel.usernameText
        .asObservable()
        .bind(to: self.emailRow!.rx.value)
        .disposed(by: self.disposeBag)

```

which has showed to respond when tested with:
```
    self.viewModel.usernameText
        .asObservable()
        .subscribe(onNext: { value in
            print("self.viewModel.usernameText did change to \(String(describing: value))")
        })
        .disposed(by: self.disposeBag)
```

A simple breakpoint and investigation into wanting to see proof that my `self.viewModel.usernameText` value has indeed changed results in: 

> EXC_BAD_ACCESS

 within the console.

![image](https://user-images.githubusercontent.com/1434449/36800421-816fc840-1c7d-11e8-881b-9c6a476a2f6f.png)

![image](https://user-images.githubusercontent.com/1434449/36800410-7c324254-1c7d-11e8-949d-3667839ea0ca.png)

![image](https://user-images.githubusercontent.com/1434449/36800474-a3a3cbc8-1c7d-11e8-9449-70ff2b21a755.png)

**Comment by antoninbiret** [comment]
Hi @sedwo. 

Could you provide a sample project where this bug can be reproduced easily ? 

Thanks

**Comment by sedwo** [comment]
Well, after some time it seems that Xcode is printing the correct values within the console.  (weird)  :/
I think Apple needs to improve Xcode's 'intellisense' some more.
