### ISSUE TITLE
Carthage doesn't seems to work

### ISSUE THREAD

**Issue by deceroainfinito** [antoninbiret/RxEureka#19]
Hi,

Trying to use Carthage to include your library it's pointing me this

```
Targ|feature/eureka_try⚡ ⇒ carthage update
*** Fetching RxEureka
*** Checking out RxEureka at "0.2.1"
*** xcodebuild output can be found in /var/folders/hr/pwfk8qcn2lz77z5bwjrzshmc0000gn/T/carthage-xcodebuild.hnhRaN.log
*** Skipped building RxEureka due to the error:
Dependency "RxEureka" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/antoninbiret/RxEureka/issues/new
```

Any ideas? Googling "Dependency "" has no shared framework schemes" didn't work for me.

**Comment by antoninbiret** [comment]
@marbetschar Do you have an idea ?

**Comment by marbetschar** [comment]
seems like Carthage tries to checkout `RxEureka` at version `v0.2.1` which does not yet include Carthage support.

@deceroainfinito can you point Carthage to the master branch for now? For this, make sure your `Cartfile`contains the following line:

```
github "antoninbiret/RxEureka" "master"
```

@antoninbiret please create a new release (just a tagged version on GitHub) so people can point to it 👍🏼

**Comment by deceroainfinito** [comment]
Thanks @marbetschar ! "master" was the solution. Didn't check v0.2.1 did not include the Carthage support commit.

**Comment by antoninbiret** [comment]
Thanks @marbetschar, it makes sense. I created a new version `0.2.2`. It should work without pointing to the `master` branch.
