### ISSUE TITLE
Good job ,but there are some compile errors

### ISSUE THREAD

**Issue by carlosbdw** [antoninbiret/RxEureka#4]
Even though I pod install & set Eureka to use swift 4.0

/GitHub/RxEureka/Example/Pods/Eureka/Source/Core/Section.swift:206:1: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent

/GitHub/RxEureka/Example/Pods/Eureka/Source/Core/Section.swift:232:1: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

/GitHub/RxEureka/Example/Pods/Eureka/Source/Core/Section.swift:206:1: Type 'Section' does not conform to protocol 'BidirectionalCollection'

 I shall be very grateful if you could tell me how to compile successfully ,thank you.

**Comment by antoninbiret** [comment]
Hi @carlosbdw. 
The library is currently not compatible with swift 4.0. I'm working on the migration on a feature branch (#5)

**Comment by antoninbiret** [comment]
I merged the swift 4.0 migration. Should be fine now. Feel free to reopen the issue if you still encounter build issues.
