### ISSUE TITLE
Support for more types than `String`?

### ISSUE THREAD

**Issue by marbetschar** [antoninbiret/RxEureka#8]
Your library is very usefull in an Eureka environment. Unfortunately it seems to only support rows which do have `String` as their value type. Because of this, I have just adopted your ideas and added support for more types in my code directly. Of course, this way of doing is not in the spirit of open source but I had to move fast ;)

That said, I'll happily provide a pull request with support for additional types as soon as I find some spare time. What I basically did is a Copy & Paste of your Reactive `RowOf<String>` extension and changed the type to e.g. `Double` like this:

```
public var value: ControlProperty<Double?> {
	var base: Base? = self.base
	
	let source = Observable<Double?>.create { observer in
		base?.onChange { row in
			observer.onNext(row.value)
		}
		return Disposables.create {
			base = nil
			observer.onCompleted()
		}
	}
	let bindingObserver = BindableObserver(container: self.base) { (row, value) in
		row.value = value
	}
	return ControlProperty(values: source, valueSink: bindingObserver)
}
```

Of course Copy & Paste is not the best solution from an architectural point of view, but till now I was not able to come up with a better solution. Do you have any idea how we can solve this in a more generic way?

**Comment by marbetschar** [comment]
The best approach would be one solution which does add the reactive extension to all kind of rows automatically - even custom ones or the ones of the EurekaCommunity project.

**Comment by marbetschar** [comment]
Doh! The solution was just too easy to see 🤣 pull request added.

**Comment by antoninbiret** [comment]
Thanks for contribution. I merged your PR.
