### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by marbetschar** [antoninbiret/RxEureka#9]
Are there any plans in adding Carthage support for this library?

**Comment by antoninbiret** [comment]
I'm personally not a Carthage user so I didn't take time to do it (for now). PR is still welcome 🙂

**Comment by marbetschar** [comment]
I'll happily provide Carthage support as soon as the pull requests are merged. No pressure here. I simply need those features in my current project so I can wait for the Carthage support till the features are merged into `RxEureka` ;)

**Comment by antoninbiret** [comment]
It will be a pleasure to merge them as soon as I have your feedback on #11 😛

**Comment by marbetschar** [comment]
@antoninbiret what’s missing? :)

**Comment by antoninbiret** [comment]
Just wrote a review and forget to post it 😓. Should be visible now.
